### ISSUE TITLE
gate way disconnected

### ISSUE THREAD

**Issue by nomikk92** [Headline/Steam-Discord-Bot#11]
hello, i cannot start the bot, please help me.
[desktop.txt](https://github.com/Headline22/Steam-Discord-Bot/files/1290587/desktop.txt)

**Comment by Headline** [comment]
Hey! I've recent fixed some issues. Please try the latest version of this, and grab an API key from GitHub in order to prevent the GitHub API from limiting the bot's request. Refer to the new Settings.xml entry.

As it seems you're the first user, you might experience some bugs. Thank you for creating this issue

**Comment by Headline** [comment]
I'm going to go ahead and close this. Re open it if you're still having troubles
